### ISSUE TITLE
HOWTO on BEaST references deprecated mincbeast_bpipe

### ISSUE THREAD

**Issue by pipitone** [CobraLab/documentation#1]
Notice that the [wiki page on running BEaST](https://github.com/CobraLab/documentation/wiki/How-to-run-BEaST) refers to using `mincbeast_bpipe` whilst the README for `mincbeast_bpipe` says it is deprecated. wat do?

**Comment by raihaan** [comment]
Made some edits, now instructs to use the shiny new bpipe.  If no arguments, I will close this
