### ISSUE TITLE
Regarding preprocessing steps need to follow before running the Magetbrain

### ISSUE THREAD

**Issue by neer86upadhyay** [CobraLab/documentation#10]
Dear Gabriel, 
The introduction of Magetbrain (https://github.com/CobraLab/documentation/wiki/MAGeTBrain) suggest to perform the following  step before running the Magetbrain:

  1  Your brains are 1x1x1 mm isotropic
  2  Your brains are in RAS orientation
  3  Your brains are preprocessed and skull-stripped (extracted)
Could you please suggest which steps to follow for the preprocessing of the T1 images necessary?
Is it needed to normalize or setting origin before performing the skull stripping?

Looking forward to your answer. 

Best regards, 
Neeraj

**Comment by gdevenyi** [comment]
The suggested preprocessing is what is commonly done on native-space T1 images.

"Normalization" aka registration to a model space will change volume estimates and as such is not recommended.

https://github.com/cobralab/iterativeN3
https://github.com/CoBrALab/iterativeN4_multispectral
and
https://github.com/CoBrALab/minc-bpipe-library

are possible preprocessing tools we use, but many others have been used successfully.

For future requests, please use the proper github issues location, https://github.com/cobralab/MAGetBrain
