### ISSUE TITLE
about mb check

### ISSUE THREAD

**Issue by wj16400** [CobraLab/documentation#3]
Dear author,

I have uploaded all of the brain*_t1.mnc and brain*_labels.mnc to the input/atlases/brains/ and  input/atlases/labels/ folder respectively, and then run the order "mb check". However, an error happened,  ERROR: Labels for atlas image  /input/atlases/brains/brain1_t1.mnc not found. How can I solve this problem?

Thanks a lot!

KwuJohn

**Comment by gdevenyi** [comment]
Please open issues in the proper repository
