### ISSUE TITLE
Old CIVET python info anaconda

### ISSUE THREAD

**Issue by egarza** [CobraLab/documentation#4]
In the old CIVET wiki we wrote that we need to load `anaconda`, but now we just need to load `python`. Loading anaconda 2 or 3 will create a conflict with python 2.7.2.

**Comment by gdevenyi** [comment]
Is it possible you followed a mix of CIC and SciNet instructions?

https://github.com/CobraLab/documentation/wiki/Cortical-Thickness-&-Surface-Analysis-with-CIVET#cic-1

This doesnt' list anaconda for SciNet
