### ISSUE TITLE
Unable to create templates with ANTs

### ISSUE THREAD

**Issue by DavidMolitor92** [CobraLab/documentation#7]
Hi everybody, 
As it says in the title, I am unfortunately unable to follow the guide to create templates for usage with MAGeTbrain. 

To install ANTs I followed these instructions: 
[](https://github.com/ANTsX/ANTs/wiki/Compiling-ANTs-on-Linux-and-Mac-OS)

But when i tried to use the program as stated in 
[](https://github.com/CobraLab/documentation/wiki/ANTs-Multivariate-Template-Construction)

it didn't work and i got the following error message and other ones like this:

> -----------------------------------------------------------------------------
 FILE /home/david/home/bin/ants/bin/antsRegistration DOES NOT EXIST -- OR -- IS NOT EXECUTABLE !!! ./my-antsMultivariateTemplateConstruction2.sh will terminate.
-----------------------------------------------------------------------------
 if the file is not executable, please change its permissions. 

actually, these files do not exist. They are in the ~/code/ANTs/Scripts Folder. I don't know if the ccmake command didn't work properly or if there is another way to do this. But i tried around for quite some time now and couldn't find a solution by myself. 
Maybe someone can help me?! Thanks in advance. 
Greetings David

**Comment by gdevenyi** [comment]
This is not for ANTs support, see https://github.com/ANTsX/ANTs
