### ISSUE TITLE
Surface sampling - xfmconcat order

### ISSUE THREAD

**Issue by raihaan** [CobraLab/documentation#8]
In step 4 of https://github.com/CobraLab/documentation/wiki/Surface-Sampling-Using-CIVET-surfaces, does ```xfmconcat``` read left to right?  I did some testing with ```/data/chamal/projects/raihaan/projects/misc/reg_check/combined.xfm``` which looks like this is the case. If so, I think step 4 should read as below to go from MNI space to ```other scan``` space:

``` xfmconcat subject_dircos.xfm subject_t1_tal_invert.xfm transform_t1_to_otherscan.xfm subject_cobmined.xfm ```

**Comment by gdevenyi** [comment]
I agree, but your answer above is wrong.

Should be

xfmconcat subject_t1_tal_invert.xfm subject_dircos.xfm transform_t1_to_otherscan.xfm subject_cobmined.xfm

**Comment by raihaan** [comment]
Ok, will fix. tnx
